hammer.git: support relative package and git repository addresses
If a package or git URL is not absolute, it will be assumed to be relative
to PKG_GIT_BASE and PKG_URL_BASE environment variables. This allows user
to set up a local server containing all the packages and git repositories.

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -47,6 +47,21 @@ _pkg_info ()
 	PKG_TYPE=`echo $PKG_DATA | awk ' { print $3 } '`
 	PKG_HASH=`echo $PKG_DATA | awk ' { print $4 } '`
 	PKG_INFO=`echo $PKG_DATA | awk ' { print $5 } '`
+	if ! (echo "$PKG_URL" | grep -q '^[a-z][a-z]*://')
+	then
+		if [ "$PKG_TYPE" = "git" ]
+		then
+			URL_BASE="$PKG_GIT_BASE"
+		else
+			URL_BASE="$PKG_WWW_BASE"
+		fi
+		if [ -z "$URL_BASE" ]
+		then
+			echo "URL base for $PKG_TYPE package $P missing."
+			exit 1
+		fi
+		PKG_URL="$URL_BASE$PKG_URL"
+	fi
 }
 
 _pkg_git_verify ()
